### ISSUE TITLE
BluetoothSerial.h Not Found

### ISSUE THREAD

**Issue by ErikAugust** [NPSconsultingLLC/BluetoothClassicCordova#1]
Any idea where I may find this? Thank you!

**Comment by NPSconsultingLLC** [comment]
Hi Erik-

This is a pretty basic outline for creating a Bluetooth Classic plugin. It should be a starting point for you. The file you are looking for has been renamed to "bluetoothDongle" you will need to update references to that to fix the issue.

**Comment by NPSconsultingLLC** [comment]
Updated this should fix this issue(but is untested, I don't have access beyond mobile at the moment)

**Comment by ErikAugust** [comment]
Awesome. Thanks so much, Nathan. I'll make some updates in my fork.

On Mon, Nov 2, 2015 at 1:50 PM, Nathan Stryker notifications@github.com
wrote:

> Closed #1
> https://github.com/NPSconsultingLLC/BluetoothClassicCordova/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NPSconsultingLLC/BluetoothClassicCordova/issues/1#event-452459646
> .

## 

Erik August Johnson
erikaugust.com
(802) 343-4640

**Comment by NPSconsultingLLC** [comment]
No problem! Good luck with your project.
